fix(ci): add fake changes to ionic_capacitor 2

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -276,12 +276,17 @@ jobs:
               BUTTONS="${BUTTONS}]"
               BUTTONS=$(echo "$BUTTONS" | sed 's/,]/]/')
 
-              curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
-                -d "chat_id=${TELEGRAM_CHAT_ID}" \
-                -d "message_thread_id=${TELEGRAM_CHAT_THREAD_ID}" \
-                -d "parse_mode=Markdown" \
-                -d "disable_web_page_preview=true" \
-                -d "text=${TG_NOTES}" \
-                -d "reply_markup={\"inline_keyboard\":${BUTTONS}}"
+              # --- отправка с обработкой ошибок
+              if ! curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
+                    -d "chat_id=${TELEGRAM_CHAT_ID}" \
+                    -d "message_thread_id=${TELEGRAM_CHAT_THREAD_ID}" \
+                    -d "parse_mode=Markdown" \
+                    -d "disable_web_page_preview=true" \
+                    -d "text=${TG_NOTES}" \
+                    -d "reply_markup={\"inline_keyboard\":${BUTTONS}}"; then
+                  echo "⚠️ Telegram send failed!"
+                  echo "TG_NOTES: $TG_NOTES"
+                  echo "BUTTONS: $BUTTONS"
+              fi
             fi
           done
